from typing import Any, List, Optional, Union, Callable

class _Sidebar:
    def title(self, text: str) -> None: ...
    def radio(self, label: str, options: List[Any], **kwargs: Any) -> Any: ...
    def selectbox(self, label: str, options: List[Any], **kwargs: Any) -> Any: ...
    def slider(self, label: str, min_value: Union[int, float], max_value: Union[int, float], value: Union[int, float], step: Union[int, float] = None, **kwargs: Any) -> Union[int, float]: ...

class _DeltaGenerator:
    def __call__(self, obj: Any) -> None: ...
    def title(self, text: str) -> None: ...
    def header(self, text: str) -> None: ...
    def subheader(self, text: str) -> None: ...
    def text(self, text: str) -> None: ...
    def markdown(self, text: str, unsafe_allow_html: bool = False) -> None: ...
    def metric(self, label: str, value: Any, delta: Optional[Any] = None, delta_color: Optional[str] = None) -> None: ...
    def plotly_chart(self, figure: Any) -> None: ...
    def write(self, obj: Any) -> None: ...
    def columns(self, n: int) -> List[_DeltaGenerator]: ...

def set_page_config(page_title: str, page_icon: str, layout: str, initial_sidebar_state: str) -> None: ...
def title(text: str) -> None: ...
def header(text: str) -> None: ...
def subheader(text: str) -> None: ...
def text(text: str) -> None: ...
def markdown(text: str, unsafe_allow_html: bool = False) -> None: ...
def metric(label: str, value: Any, delta: Optional[Any] = None, delta_color: Optional[str] = None) -> None: ...
def plotly_chart(figure: Any) -> None: ...
def write(obj: Any) -> None: ...
def columns(n: int) -> List[_DeltaGenerator]: ...

sidebar: _Sidebar
